version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: datageek_mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
    networks:
      - datageek_network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: datageek_redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - datageek_network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: datageek_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=datageek_pg_admin
      - POSTGRES_PASSWORD=DataGeek_PG_2024
      - POSTGRES_DB=datageek
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - datageek_network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  datageek_network:
    driver: bridge