version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: datageek_mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: datageek_admin
      MONGO_INITDB_ROOT_PASSWORD: DataGeek_Admin_2024
      MONGO_INITDB_DATABASE: datageek
    volumes:
      - mongodb_data:/data/db
    networks:
      - datageek_network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: datageek_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - datageek_network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  datageek_network:
    driver: bridge